[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
auto_detect_solc = false
solc_version = "0.8.19"

[rpc_endpoints]
sepolia = '${SEPOLIA_RPC}'
localhost = '${LOCAL_RPC}'
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
